// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("gatewayauth")
	ScopeName = "github.com/dmathieu/gatewayauth"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
