name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Lint
      run: make lint
