name: Test
on: [push, pull_request]
jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Test
      run: make test
